### ISSUE TITLE
Is it possible to integrate this with pmndrs/postprocessing? 

### ISSUE THREAD

**Issue by kitaedesigns** [washington254/realism-effect#1]
Is it possible to integrate this with pmndrs/postprocessing? Asking in particular about SSR and Motion Blur. 

They have what is probably the best/most used postprocessing library with three.js, and the only effects their effects chain is missing is really the stuff in realism-effect. I'm not the most knowledgeable on this front but wondering how they could be combined?

https://github.com/pmndrs/postprocessing

**Comment by washington254** [comment]
hey happy you found the project useful. realism effect uses pmndrs/postprocessing albeit an earlier version. v 6.31.0 to be exact. upgrading to the latest version might break some features so i didn't bother doing it. but of course if a lot of people use it i might upgrade it. but i figured the pmndrs team is working to add the said effects on v7 so this won't be really useful after sometime  https://github.com/pmndrs/postprocessing/releases/tag/v6.31.0
